default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: admin
  password: 8772222
development: &development
  <<: *default
  database: micropostg_development

# The staging, preproduction and production dbs are only needed
# for running rake assets:precompile locally before deploying
staging:
  <<: *development

production:
  database: micropostg_production

test:
  <<: *default
  database: micropostg_test
